### ISSUE TITLE
Does not work on macOS due to line endings

### ISSUE THREAD

**Issue by timbru31** [HansHammel/license-compatibility-checker#1]
After installing on macOS I'm unable to run the cli (`$ license-compatibility-checker`) because of the error:

`env: node\r: No such file or directory`

It seems you have uploaded the files CRLF line endings instead of LF.  
Could you possibly switch to LF? (e.g. via `.gitattributes` or `.editorconfig`)

**Comment by edouard-lopez** [comment]
same on Linux Mint/Ubuntu

**Comment by majnu-campact** [comment]
Same problem here on macOS. Any chance that this will be fixed?

**Comment by HansHammel** [comment]
Cannot reproduce the issue. I published a new version and added a bin script test. On travis mac and linux builds are all passing. So, I am closing this for now.
