### ISSUE TITLE
AGPL-3.0-only and AGPL-3.0-or-later

### ISSUE THREAD

**Issue by echamudi** [HansHammel/license-compatibility-checker#10]
Hello HansHammel,
Can you add these AGPL variants?
```
AGPL-3.0-only
AGPL-3.0-or-later
AGPL-1.0-only
AGPL-1.0-or-later
```
Source: https://spdx.org/licenses/
Thanks for the nice project you have!

**Comment by HansHammel** [comment]
Done. These licenses are strong network protective - as far as i can tell...
