### ISSUE TITLE
new Eclipse license version 2.0 needs adding

### ISSUE THREAD

**Issue by robbiemorrison** [HansHammel/license-compatibility-checker#2]
The Eclipse Foundation announced version 2.0 on 24 August 2017.

- https://en.wikipedia.org/wiki/Eclipse_Public_License
- https://en.wikipedia.org/wiki/Eclipse_Public_License#Version_2.0

This license is a bit complicated because the initial committer **can opt in to** GPLv2+ (version 2 or any later version) as part of this license. The wikipedia page mentioned above contains more details and links to primary references.

cheers, Robbie

**Comment by HansHammel** [comment]
Done. ^GPLv2+ compatiblity makes this still a strongly protective license
