### ISSUE TITLE
Exit code 127 with yarn

### ISSUE THREAD

**Issue by yuhr** [HansHammel/license-compatibility-checker#4]
`yarn license-compatibility-checker` emits

```
env: node\r: No such file or directory
error Command failed with exit code 127.
```

while `npx license-compatibility-checker` successfully runs.

- node 11.3.0
- yarn 1.12.3
- license-compatibility-checker 0.3.3

**Comment by HansHammel** [comment]
https://github.com/yarnpkg/yarn/issues/5480
