### ISSUE TITLE
More options on error handling

### ISSUE THREAD

**Issue by helio-frota** [HansHammel/license-compatibility-checker#5]
Hi, 

I'm using `license-compatibility-checker` as module. When I execute the code I see this error message:

```console
{ [Error: ENOENT: no such file or directory, access '/home/hf/Desktop/license-reporter/node_modules/@babel/package.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path:
   '/home/hf/Desktop/license-reporter/node_modules/@babel/package.json' }
```

Any chance to suppress this kind of error?
thanks

**Comment by HansHammel** [comment]
This is a permission error by the os, so throwing here is perfectly valid because  there is no chance to program to work without permissions. Closing...
